### ISSUE TITLE
How to play 180 videos ?

### ISSUE THREAD

**Issue by LeoFabre** [picoxr/VideoPlayer#3]
Hello,
I would like to play 180° videos in a Pico G2 4K.

I tried playing them in the 360_player scene, but as expected, they are stretched to the whole 360 degrees of the sphere.

I would like the video to take only the half of the sphere so that it is not wierdly stretched all around.

How would I go about implementing this ?

EDIT: I will also need to play 360 top-bottom videos, and I would need indications for that also. Thank you :)

Thanks in advance.
Leo Fabre

**Comment by picoxr** [comment]
Playing 180° videos requires you to make the halfsphere model and have a corresponding shader.
 For playing 360 top-bottom Videos, you can refer to the 3D-over-Under scene.

**Comment by LeoFabre** [comment]
Alright, got a custom shader working (there may be a better way to achieve this) : 
https://pastebin.com/FdxAcb7a

If anyone needs to use it, just put it on your sphere, then to set the tiling vector, do something like :
`            _player.gameObject.GetComponent<MeshRenderer>().sharedMaterial.SetVector("_Mod", new Vector4(2, 1, -.5f, 0));
`

Also, I figured out how to play 360 and 180 in 3D by reproducing the behavior of your Widescreen 3D scenes, works like a charm after some script adaptation.

Honestly, I think you guys should provide this functionality in the repo, as many businesses will want to achieve spherical 3D playback. 

Thanks again !
Leo Fabre
