### ISSUE TITLE
Issues reading several videos from SD card

### ISSUE THREAD

**Issue by LeoFabre** [picoxr/VideoPlayer#4]
I am trying to play 3840*2160 30fps 50000kb/s videos from the sdcard, they just won't play,

There are no specific errors in the console

When I try to play it from internal storage there is no problem and playback is smooth.
My sdcard is Sandisk ultra 64gb Class10 A1 XC1.

I have no problem playing lower-res videos from the sdcard.

Please let me know if you can give me some advice.

**Comment by LeoFabre** [comment]
Just so you know, the native pico video player app seems to play the video well from the sdcard when i run it from the explorer, in cinema mode. I need to build a spherical player for it.

**Comment by picoxr** [comment]
The path of sdcard is not fixed, so you need to get the path first. This is the Demo to get the sdcard path. https://github.com/picoxr/get-sd-card-path

**Comment by LeoFabre** [comment]
Thank you very much. I was already using this method, and i can confirm that :
- This works for all the other videos 
- File.Exists(videoPath) returns true for the video i am trying to play. (videopath = path.Combine(getSDCardPath, videoFileName)

I told that there was no Errors, but there is a warning that didn't catch my attention until now : 

I am getting a "AndroidVideoMedia : no tracks in <the file path>" warning.

Again, the path is correct for sure, and the headset will play the video natively without any problems, from the sd card.

Thanks in advance.

**Comment by picoxr** [comment]
We found that the reason for "AndroidVideoMedia: No track in <file path>" was that the video stream could not be found. 
Can you provide a video to support@picovr.com

**Comment by LeoFabre** [comment]
Hello, I have just sent you a sample video that produces the bug when played. 
Please notice that i don't use it as a Unity Video Clip asset, but rather as a **URL** to pass to the VideoPlayer.

Thank you very much in advance !

**Comment by picoxr** [comment]
Your video can play normally when I put it on SD card.You can test it with this project.
https://drive.google.com/file/d/1aTrPP-5xoTE8CZiMQssPNXlxHDXAACpM/view?usp=sharing
![image](https://user-images.githubusercontent.com/46362299/99480730-a29c0f80-2993-11eb-8342-72cd6a08f5af.png)

**Comment by LeoFabre** [comment]
Hello, 
I have answered your email, the issue still reproduces with the project you sent me.

Please read my email for further details on what I exactly did to reproduce the behavior.

Thank you very much

**Comment by LeoFabre** [comment]
Could you please try to send me an APK that will try to play "video.mp4" at the root of the sdcard ? I'll run it and will send you log info.

Thanks in advance

**Comment by picoxr** [comment]
This link is a test APK.
https://drive.google.com/file/d/1MEsdm-YfTxfJQfDlGTCazQFoQKuGtLMF/view?usp=sharing
![image](https://user-images.githubusercontent.com/46362299/99611303-62e62e00-2a4e-11eb-9b30-1d55749085a9.png)

**Comment by LeoFabre** [comment]
Hello !

The problem was that I had to give "file:///" at the start of the videoPlayer's URL.

It is weird that all the other videos were working without the prefix, but hey, problem is gone now, boss is happy, and so am I 👍 

Thank you and sorry :)
